import type { Word } from "./types";

/**
 * A small hand-written bank. Each entry carries `keys`: the content words a
 * correct answer usually contains. The offline grader scores overlap against
 * these, so adding a word means adding good keys, not just a definition.
 */
export const WORDS: Word[] = [
  {
    id: "ubiquitous",
    word: "ubiquitous",
    pos: "adjective",
    definition: "Present everywhere at the same time; found in all places.",
    example: "Smartphones are ubiquitous in modern cities.",
    keys: ["everywhere", "present", "common", "all", "places", "widespread", "omnipresent"],
    difficulty: 1,
  },
  {
    id: "candid",
    word: "candid",
    pos: "adjective",
    definition: "Honest and direct, especially about something uncomfortable.",
    example: "She gave a candid account of why the project failed.",
    keys: ["honest", "direct", "frank", "truthful", "open", "blunt"],
    difficulty: 1,
  },
  {
    id: "meticulous",
    word: "meticulous",
    pos: "adjective",
    definition: "Showing great attention to detail; very careful and precise.",
    example: "His meticulous notes made the handover painless.",
    keys: ["careful", "detail", "precise", "thorough", "attention", "exact"],
    difficulty: 1,
  },
  {
    id: "resilient",
    word: "resilient",
    pos: "adjective",
    definition: "Able to recover quickly from difficulty or setbacks.",
    example: "The team proved resilient after losing two key engineers.",
    keys: ["recover", "bounce", "back", "tough", "withstand", "setback", "difficulty"],
    difficulty: 1,
  },
  {
    id: "ambiguous",
    word: "ambiguous",
    pos: "adjective",
    definition: "Open to more than one interpretation; unclear in meaning.",
    example: "The contract was ambiguous about who owned the data.",
    keys: ["unclear", "vague", "interpretation", "meaning", "two", "uncertain", "confusing"],
    difficulty: 1,
  },
  {
    id: "pragmatic",
    word: "pragmatic",
    pos: "adjective",
    definition: "Dealing with things practically rather than by theory or ideals.",
    example: "We took a pragmatic approach and shipped the simpler version.",
    keys: ["practical", "realistic", "sensible", "theory", "useful", "results"],
    difficulty: 1,
  },
  {
    id: "scrutinize",
    word: "scrutinize",
    pos: "verb",
    definition: "To examine something closely and critically.",
    example: "Auditors scrutinized every line of the expense report.",
    keys: ["examine", "inspect", "closely", "carefully", "study", "check", "critically"],
    difficulty: 1,
  },
  {
    id: "alleviate",
    word: "alleviate",
    pos: "verb",
    definition: "To make a problem or suffering less severe.",
    example: "The new caching layer alleviated most of the latency complaints.",
    keys: ["reduce", "ease", "lessen", "relieve", "less", "severe", "suffering", "pain"],
    difficulty: 2,
  },
  {
    id: "tenacious",
    word: "tenacious",
    pos: "adjective",
    definition: "Holding firmly to a goal or opinion; persistent and stubborn.",
    example: "Her tenacious follow-up eventually landed the meeting.",
    keys: ["persistent", "determined", "stubborn", "firm", "grip", "refuses", "give", "up"],
    difficulty: 2,
  },
  {
    id: "prudent",
    word: "prudent",
    pos: "adjective",
    definition: "Acting with care and good judgement about the future.",
    example: "It was prudent to keep three months of runway.",
    keys: ["careful", "wise", "cautious", "sensible", "judgement", "risk", "future"],
    difficulty: 2,
  },
  {
    id: "innocuous",
    word: "innocuous",
    pos: "adjective",
    definition: "Harmless; unlikely to offend or cause injury.",
    example: "The bug looked innocuous until it hit production.",
    keys: ["harmless", "safe", "innocent", "mild", "offend", "injury", "danger"],
    difficulty: 2,
  },
  {
    id: "reticent",
    word: "reticent",
    pos: "adjective",
    definition: "Unwilling to speak freely; reserved about one's thoughts.",
    example: "He was reticent about why he left his last job.",
    keys: ["quiet", "reserved", "silent", "unwilling", "speak", "share", "withheld", "shy"],
    difficulty: 2,
  },
  {
    id: "juxtapose",
    word: "juxtapose",
    pos: "verb",
    definition: "To place two things side by side to highlight the contrast.",
    example: "The slide juxtaposed our uptime with the industry average.",
    keys: ["side", "place", "compare", "contrast", "together", "next", "two"],
    difficulty: 2,
  },
  {
    id: "galvanize",
    word: "galvanize",
    pos: "verb",
    definition: "To shock or excite a group into taking action.",
    example: "The outage galvanized the team into rewriting the deploy script.",
    keys: ["motivate", "spur", "excite", "action", "energize", "stir", "rouse", "prompt"],
    difficulty: 2,
  },
  {
    id: "ephemeral",
    word: "ephemeral",
    pos: "adjective",
    definition: "Lasting for a very short time.",
    example: "The hype was ephemeral; the product survived.",
    keys: ["short", "brief", "temporary", "fleeting", "time", "lasting", "moment"],
    difficulty: 3,
  },
  {
    id: "obfuscate",
    word: "obfuscate",
    pos: "verb",
    definition: "To deliberately make something unclear or hard to understand.",
    example: "The report obfuscated the real cause of the loss.",
    keys: ["confuse", "unclear", "hide", "obscure", "muddle", "understand", "deliberately"],
    difficulty: 3,
  },
  {
    id: "esoteric",
    word: "esoteric",
    pos: "adjective",
    definition: "Understood by only a small group with specialised knowledge.",
    example: "The talk drifted into esoteric details of the compiler.",
    keys: ["obscure", "specialised", "few", "small", "knowledge", "niche", "understood", "insiders"],
    difficulty: 3,
  },
  {
    id: "intransigent",
    word: "intransigent",
    pos: "adjective",
    definition: "Refusing to change one's position or compromise.",
    example: "The vendor stayed intransigent on pricing.",
    keys: ["stubborn", "refusing", "compromise", "unyielding", "inflexible", "change", "position"],
    difficulty: 3,
  },
  {
    id: "laconic",
    word: "laconic",
    pos: "adjective",
    definition: "Using very few words; terse to the point of seeming blunt.",
    example: "His laconic reply was a single word: shipped.",
    keys: ["brief", "few", "words", "short", "terse", "concise", "blunt"],
    difficulty: 3,
  },
  {
    id: "quixotic",
    word: "quixotic",
    pos: "adjective",
    definition: "Idealistic and impractical to the point of being unrealistic.",
    example: "Rewriting the whole stack in a week was a quixotic plan.",
    keys: ["idealistic", "unrealistic", "impractical", "dreamer", "romantic", "hopeless", "foolish"],
    difficulty: 3,
  },
  {
    id: "perfunctory",
    word: "perfunctory",
    pos: "adjective",
    definition: "Done as a routine duty, with minimal care or interest.",
    example: "He gave the document a perfunctory glance and signed it.",
    keys: ["careless", "routine", "minimal", "quick", "interest", "effort", "superficial", "duty"],
    difficulty: 3,
  },
  {
    id: "ostensible",
    word: "ostensible",
    pos: "adjective",
    definition: "Stated as true but likely not the real reason.",
    example: "The ostensible reason for the delay was weather.",
    keys: ["apparent", "stated", "claimed", "supposed", "real", "reason", "seems", "surface"],
    difficulty: 3,
  },
  {
    id: "capitulate",
    word: "capitulate",
    pos: "verb",
    definition: "To stop resisting and accept the other side's demands.",
    example: "After three rounds of review, we capitulated on the deadline.",
    keys: ["surrender", "give", "up", "yield", "submit", "concede", "stop", "resisting"],
    difficulty: 3,
  },
  {
    id: "extol",
    word: "extol",
    pos: "verb",
    definition: "To praise something enthusiastically.",
    example: "The post extolled the virtues of shipping small.",
    keys: ["praise", "compliment", "admire", "highly", "glorify", "celebrate", "enthusiastically"],
    difficulty: 3,
  },
];

export function wordsByDifficulty(max: number): Word[] {
  return WORDS.filter((w) => w.difficulty <= max);
}
